### ISSUE TITLE
Create frontend for viewing and updating tasks on user dashboard

### ISSUE THREAD

**Issue by LeNPaul** [LeNPaul/productivity-system-app#11]
This task helps achieve user story #6

#### Task

Create frontend for viewing and updating tasks on user dashboard using vue.js

#### Acceptance Criteria

- [x] Set up vue.js to-do list frontend
- [x] Able to create a task from the user dashboard
- [x] Able to update a task from the user dashboard
