### ISSUE TITLE
Create placeholder pages for home, login, register, and user dashboard

### ISSUE THREAD

**Issue by LeNPaul** [LeNPaul/productivity-system-app#4]
This task helps achieve user story #5

#### Task

Create basic placeholder pages for home, login, register, and user dashboard

#### Acceptance Criteria

- [x] Add home page
- [x] Add login and register page
- [x] Add user dashboard page
